# Generated by Django 5.0.4 on 2025-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('guest', 'Guest')], default='guest', max_length=30),
        ),
    ]
