# Generated by Django 5.0.4 on 2025-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='sponsored_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
