# Generated by Django 4.2 on 2025-05-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_comment_user_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_likes', to='base.article')),
            ],
            options={
                'verbose_name': 'Anonymous Like',
                'verbose_name_plural': 'Anonymous Likes',
                'unique_together': {('article', 'session_key')},
            },
        ),
    ]
